config:
  plugin:
    metrics-by-endopoint: {}
  target: "http://localhost:8080"
  phases: 
    - duration: 20
      arrivalRate: 10
scenarios: 
  - name: "Sessions flow (register + login)"
    flow: 
      - log: "Creamos las variables para el usuario de prueba."
      - get:
          url: "/api/users/fakeruser"
          capture: 
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.age"
              as: "age"
            - json: "$.password"
              as: "password"
      - log: "Registrando al usuario:"
      - post: 
          url: "/api/users/register"
          json: 
            first_name: "{{first_name}}"
            last_name: "{{last_name}}"
            email: "{{email}}"
            age: "{{age}}"
            password: "{{password}}"
      - think: 2 
      - log: "Login User"
      - post:
          url: "/api/users/login"
          json: 
            email: "{{email}}" 
            password: "{{password}}"